# Generated by Django 5.2.17 on 2026-09-11 15:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone_numbers', models.CharField(blank=True, help_text='Comma-separated', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('disclaimer', models.TextField(blank=True, default='Prices are subject to variations in market conditions')),
                ('payment_terms', models.TextField(blank=True)),
                ('quote_validity', models.CharField(blank=True, max_length=255)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('7.50'), help_text='Percentage. Set to 0 if VAT does not apply.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
