# Generated by Django 5.2.17 on 2026-09-12 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('price_changed', 'Price changed'), ('bank_changed', 'Bank details changed'), ('quote_created', 'Quote created'), ('quote_updated', 'Quote edited'), ('quote_sent', 'Quote sent'), ('quote_revised', 'Quote revised'), ('quote_deleted', 'Quote deleted')], max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, help_text='Quote reference or catalogue entry.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='accounts.businessprofile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
