# Generated by Django 5.2.17 on 2026-09-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='brand_logo',
            field=models.ImageField(blank=True, help_text='Logo of the manufacturer whose cables you distribute, shown beside your own.', upload_to='logos/'),
        ),
    ]
