# Generated by Django 5.2.17 on 2026-09-23 12:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_backfill_owner_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='store_limit',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum active stores. Operator-set; the business cannot change it.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(help_text='Short branch code used in reference numbers, e.g. IKJ.', max_length=8)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.businessprofile')),
            ],
            options={
                'ordering': ['business_id', 'name'],
                'constraints': [models.UniqueConstraint(fields=('business', 'code'), name='one_store_code_per_business')],
            },
        ),
    ]
