# Generated by Django 5.2.17 on 2026-09-23 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_backfill_first_store'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='all_stores',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='role_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='membership',
            name='stores',
            field=models.ManyToManyField(blank=True, related_name='members', to='accounts.store'),
        ),
        migrations.CreateModel(
            name='RoleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_templates', to='accounts.businessprofile')),
            ],
            options={
                'ordering': ['business_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('role_label', models.CharField(blank=True, max_length=50)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('all_stores', models.BooleanField(default=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.businessprofile')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('stores', models.ManyToManyField(blank=True, related_name='invitations', to='accounts.store')),
                ('role_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='accounts.roletemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='role_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='accounts.roletemplate'),
        ),
        migrations.AddConstraint(
            model_name='roletemplate',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='one_template_name_per_business'),
        ),
    ]
