# Generated by Django 5.2.17 on 2026-09-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_drop_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='show_factory_price',
            field=models.BooleanField(default=False, help_text="Show the manufacturer's direct price on quotes, so customers see what they save."),
        ),
    ]
