# Generated by Django 5.2.17 on 2026-09-23 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_quote_payment_override_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log', to='accounts.store'),
        ),
    ]
