# Generated by Django 5.2.17 on 2026-09-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_member_audit_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('price_changed', 'Price changed'), ('bank_changed', 'Bank details changed'), ('quote_payment_override', 'Quote payment account overridden'), ('member_invited', 'Staff member invited'), ('member_changed', 'Staff access changed'), ('line_discounted', 'Quote line sold below the catalogue price'), ('quote_created', 'Quote created'), ('quote_updated', 'Quote edited'), ('quote_sent', 'Quote sent'), ('quote_revised', 'Quote revised'), ('quote_deleted', 'Quote deleted'), ('purchase_recorded', 'Purchase recorded'), ('purchase_deleted', 'Purchase deleted'), ('waybill_created', 'Waybill created'), ('waybill_updated', 'Waybill edited'), ('waybill_deleted', 'Waybill deleted')], max_length=32),
        ),
    ]
