# Generated by Django 5.2.17 on 2026-09-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_grant_discount_to_existing'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='restricted_reason',
            field=models.CharField(blank=True, help_text="Shown to the business when a write is refused, e.g. 'Trial ended — contact sales'.", max_length=200),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('restricted', 'Restricted — read-only')], default='active', help_text='Restricted makes the business read-only. Their records stay readable and downloadable.', max_length=20),
        ),
    ]
