# Generated by Django 5.2.17 on 2026-09-13 10:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_auditlog_action'),
        ('catalogue', '0004_accessory_average_unit_cost_accessory_last_unit_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('additional_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Transport, clearing and loading for this delivery.', max_digits=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('1000000000'))])),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='What was bought, as it read at the time.', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='How many of entry_unit arrived.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100000'))])),
                ('entry_unit', models.CharField(choices=[('coil', 'Coil (100m)'), ('metre', 'Metre'), ('piece', 'Piece'), ('pack', 'Pack'), ('box', 'Box'), ('roll', 'Roll'), ('length', 'Length'), ('set', 'Set')], max_length=10)),
                ('units_per_entry', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Sale units in one entry unit: 100 when a coil is sold by the metre.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100000'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, help_text='Paid per entry_unit, before transport.', max_digits=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('1000000000'))])),
                ('landed_unit_cost', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=17, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='catalogue.accessory')),
                ('cable_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='catalogue.cablesize')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchasing.purchase')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
