# Generated by Django 5.2.17 on 2026-09-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='item_name',
            field=models.CharField(help_text='What was bought, as it read at the time.', max_length=255),
        ),
    ]
