# Generated by Django 5.2.17 on 2026-09-15 13:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_auditlog_action'),
        ('catalogue', '0006_seed_price_history'),
        ('quotes', '0006_quotelineitem_cost_basis_quotelineitem_unit_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=32)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('customer_name', models.CharField(help_text='Printed as "M/S".', max_length=200)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=30)),
                ('product_manufacturer', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waybills', to='accounts.businessprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybills', to='quotes.quote')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WaybillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cable', 'Cable'), ('accessory', 'Accessory')], default='cable', max_length=10)),
                ('cable_type_name', models.CharField(blank=True, max_length=100)),
                ('size_label', models.CharField(blank=True, max_length=100)),
                ('item_name', models.CharField(blank=True, max_length=150)),
                ('unit', models.CharField(choices=[('coil', 'Coil (100m)'), ('metre', 'Metre'), ('piece', 'Piece'), ('pack', 'Pack'), ('box', 'Box'), ('roll', 'Roll'), ('length', 'Length'), ('set', 'Set')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('accessory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_items', to='catalogue.accessory')),
                ('cable_size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waybill_items', to='catalogue.cablesize')),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='waybills.waybill')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WaybillItemColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('100000'))])),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colours', to='waybills.waybillitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='waybill',
            constraint=models.UniqueConstraint(fields=('business', 'reference_number'), name='unique_waybill_reference_per_business'),
        ),
    ]
