# Generated by Django 5.2.17 on 2026-09-11 15:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=32)),
                ('customer_name', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('staff_name', models.CharField(max_length=200)),
                ('staff_phone', models.CharField(blank=True, max_length=50)),
                ('product_manufacturer', models.CharField(blank=True, max_length=200)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='accounts.businessprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cable_type_name', models.CharField(max_length=100)),
                ('size_label', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('coil', 'Coil (100m)'), ('metre', 'Metre')], max_length=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('cable_size', models.ForeignKey(blank=True, help_text='Catalogue entry this line came from, kept for future cost and stock tracking. Display uses the snapshot fields.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_line_items', to='catalogue.cablesize')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='quotes.quote')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteLineItemColour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colours', to='quotes.quotelineitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('business', 'reference_number'), name='unique_quote_reference_per_business'),
        ),
    ]
