# Generated by Django 5.2.17 on 2026-09-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_accessory'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelineitem',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_line_items', to='catalogue.accessory'),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='item_name',
            field=models.CharField(blank=True, help_text='Accessory name. Cables use type and size.', max_length=150),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='kind',
            field=models.CharField(choices=[('cable', 'Cable'), ('accessory', 'Accessory')], default='cable', max_length=10),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='cable_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_line_items', to='catalogue.cablesize'),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='cable_type_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='size_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='unit',
            field=models.CharField(choices=[('coil', 'Coil (100m)'), ('metre', 'Metre'), ('piece', 'Piece'), ('pack', 'Pack'), ('box', 'Box'), ('roll', 'Roll'), ('length', 'Length'), ('set', 'Set')], max_length=10),
        ),
    ]
