# Generated by Django 5.2.17 on 2026-09-12 10:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quotelineitem_accessory_quotelineitem_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='payment_account_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='quote',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('1000000000'))]),
        ),
        migrations.AlterField(
            model_name='quotelineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('1000000000'))]),
        ),
        migrations.AlterField(
            model_name='quotelineitemcolour',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('100000'))]),
        ),
    ]
