# Generated by Django 5.2.17 on 2026-09-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_backfill_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='revision_of',
            field=models.ForeignKey(blank=True, help_text='The sent quote this one was raised to replace.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='quotes.quote'),
        ),
        migrations.AddField(
            model_name='quote',
            name='sent_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
