# Generated by Django 5.2.17 on 2026-09-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_revision_of_quote_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotelineitem',
            name='cost_basis',
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=17, null=True),
        ),
    ]
