# Generated by Django 5.2.17 on 2026-09-23 13:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_quotelineitem_cost_basis_quotelineitem_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='show_factory_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotelineitem',
            name='factory_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('1000000000'))]),
        ),
    ]
