# Generated by Django 5.2.17 on 2026-09-23 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_store_scoping'),
        ('quotes', '0007_factory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='accounts.store'),
        ),
    ]
