# Generated by Django 5.2.17 on 2026-09-11 15:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CableType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('coil', 'Coil (100m)'), ('metre', 'Metre')], default='coil', max_length=10)),
                ('has_colour_variants', models.BooleanField(default=False)),
                ('colour_options', models.JSONField(blank=True, default=list, help_text='e.g. ["Red", "Black", "Yellow/Green"]')),
                ('order', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cable_types', to='accounts.businessprofile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CableSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(max_length=100)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('cable_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='catalogue.cabletype')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='cabletype',
            constraint=models.UniqueConstraint(fields=('business', 'name'), name='unique_cable_type_name_per_business'),
        ),
        migrations.AddConstraint(
            model_name='cablesize',
            constraint=models.UniqueConstraint(fields=('cable_type', 'size_label'), name='unique_size_label_per_cable_type'),
        ),
    ]
