# Generated by Django 5.2.17 on 2026-09-11 20:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('pack', 'Pack'), ('box', 'Box'), ('roll', 'Roll'), ('length', 'Length'), ('set', 'Set'), ('metre', 'Metre')], default='piece', max_length=10)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='accounts.businessprofile')),
            ],
            options={
                'verbose_name_plural': 'accessories',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('business', 'name'), name='unique_accessory_name_per_business')],
            },
        ),
    ]
