# Generated by Django 5.2.17 on 2026-09-12 10:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_accessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='default_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('1000000000'))]),
        ),
        migrations.AlterField(
            model_name='cablesize',
            name='default_price',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('1000000000'))]),
        ),
    ]
