# Generated by Django 5.2.17 on 2026-09-13 10:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_accessory_default_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='average_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='last_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='purchase_unit',
            field=models.CharField(blank=True, help_text='What this is bought in, when that differs from how it is sold (bought by coil, sold by metre).', max_length=10),
        ),
        migrations.AddField(
            model_name='accessory',
            name='units_per_purchase',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Sale units in one purchase unit: 100 for a 100 m coil sold by the metre.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100000'))]),
        ),
        migrations.AddField(
            model_name='cablesize',
            name='average_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='cablesize',
            name='last_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=17, null=True),
        ),
        migrations.AddField(
            model_name='cablesize',
            name='purchase_unit',
            field=models.CharField(blank=True, help_text='What this is bought in, when that differs from how it is sold (bought by coil, sold by metre).', max_length=10),
        ),
        migrations.AddField(
            model_name='cablesize',
            name='units_per_purchase',
            field=models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='Sale units in one purchase unit: 100 for a 100 m coil sold by the metre.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100000'))]),
        ),
    ]
