# Generated by Django 5.2.17 on 2026-09-23 13:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_seed_price_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='factory_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What the manufacturer would charge a customer buying direct. Higher than your price.', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('1000000000'))]),
        ),
        migrations.AddField(
            model_name='accessory',
            name='factory_price_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cablesize',
            name='factory_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What the manufacturer would charge a customer buying direct. Higher than your price.', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('1000000000'))]),
        ),
        migrations.AddField(
            model_name='cablesize',
            name='factory_price_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
